### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GiannisMaster** [Lafko/Launcher#2]
I use arp wifi with the default addresses of each computer and its not working

**Comment by Lafko** [comment]
So something you do is not right

**Comment by GiannisMaster** [comment]
like? i take ipv4 address from radar pc and ipv4 address from game pc

**Comment by Lafko** [comment]
Probably a problem in the router

**Comment by GiannisMaster** [comment]
What do you suggest as a solution?

**Comment by GiannisMaster** [comment]
if i open ports with 80 tcp and udp will it work?

**Comment by Lafko** [comment]
I do not know and I do not help in setting up
